### ISSUE TITLE
Convert the weather service from using old ruuter logic with json files to the new one with yml files

### ISSUE THREAD

**Issue by ValterAro** [buerokratt/Common-Services#32]
AS A service manager
I WANT the weather service to be functional in the new bürokratt
SO THAT it would be available to be used through the bürokratt chat widget

Based on the old weather service convert the logic to yml format and make it work in the new Bürokratt 2.0 .

AC:

- [ ] yml files work as a standalone service
- [ ] end client is able to get information about the weather in a particular area in Estonia using dev chat widget

**Comment by ValterAro** [comment]
Previous json files that were used for ruuter v1.

[get-data-things.json](https://github.com/user-attachments/files/15925825/get-data-things.json)
[get-location-things.json](https://github.com/user-attachments/files/15925827/get-location-things.json)
[get-station-things.json](https://github.com/user-attachments/files/15925828/get-station-things.json)
[get-things.json](https://github.com/user-attachments/files/15925829/get-things.json)

constants:
"gazetteer_url":"https://inaadress.maaamet.ee/inaadress",
"publicapi_url": "https://publicapi.envir.ee/v1/combinedWeatherData",

**Comment by ValterAro** [comment]
Additional info:
JSON files with the previous logic for ruuter v1.
[get-data-things.json](https://github.com/user-attachments/files/15925853/get-data-things.json)
[get-location-things.json](https://github.com/user-attachments/files/15925854/get-location-things.json)
[get-station-things.json](https://github.com/user-attachments/files/15925855/get-station-things.json)
[get-things.json](https://github.com/user-attachments/files/15925856/get-things.json)

constants:
"gazetteer_url":"https://inaadress.maaamet.ee/inaadress",
"publicapi_url": "https://publicapi.envir.ee/v1/combinedWeatherData",
"ilmmicroservice_url": "https://ilmmicroservice.envir.ee/api/forecasts"

Service was initiated with a yml file:
```
checkservice:
  switch:
    - condition: ${incoming.body.list[0] === "#weather"}
      next: weatherService
    - condition: ${incoming.body.list[0] == null}
      next: noService
  next: noService

weatherService:
  call: http.post
  args:
    url: https://ruuter.buerokratt.stat.ee/get-things
    body:
     locationName: ${incoming.body.list[1]}
     chatId: ${incoming.body.chatId}
     authorId: ${incoming.body.authorId}
  result: weatherRequest
  next: end

```
